a=input('Digite algo:')
print('O tipo primitivo desse valor é:',type(a))
print('Só tem espaços?',a.isspace())
print('É um numero?',a.isnumeric())
print('É alfabético?',a.isalpha())
print('É alfanumérico?',a.isalnum())
print('É maiscúla?',a.isupper())
print('É minúscula?',a.islower())
print('É capitalizada?',a.istitle())
