frase = str(input('Digite uma frase:')).strip().upper()
print('Analisando...')
a = frase.count('A')
print(f'A letra A aparece {a} vezes')
print(f'A primeira letra A apareceu na posição {frase.find("A")+1}')
print(f'A última vez que a letra A aparece é na posição {frase.rfind('A')+1}')
