#nome=input('Digite seu nome completo:')
#print('Seu nome completo tem', len(nome.replace(' ', '')), 'letras')
#print('Seu nome em maiúsculo fica: ', nome.upper())
#print('Seu nome em minúsculo fica:', nome.lower())
#p#rint('Seu primeiro nome tem', len(nome.split()[0]), 'letras:')

nome=str(input('Digite seu nome completo:')).strip()
print('Analisando seu nome...')
print(f'Seu nome em maiscúlas é: {nome.upper()}')
print(f'Seu nome em minúsculas é: {nome.lower()}')
print(f'Seu nome tem ao todo: {len(nome) - nome.count(' ')}')
#print(f'Seu primeiro nome tem {nome.find (' ')} letras')
separa = nome.split()
print(f'seu primeiro nome é: {separa[0]} e ele tem {len(separa[0])} letras')
